# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('target_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Todoist.projects')),
            ],
        ),
    ]
